In [3]:
import numpy as np

print("单个矩阵的读写：")
arr=np.arange(10)
print(type(arr))
print(arr.dtype)
np.save('some_array',arr)                #默认保存格式为.npy(二进制文件，所以无法直接读取)
np.savetxt('some_txt',arr)               #保存为文本文件，可以之间读取
a=np.load('some_array.npy')
print(a,"\n")

print("多个矩阵的读写：")
b=np.arange(12).reshape((3,4))
np.savez('more_array',fir=a,sec=b)       
#默认格式为.npz读取时类似于字典(fir和sec是相当于创建键值对，用于查找相应数据)
c=np.load('more_array.npz')
print(c['fir'])
print(c['sec'])

单个矩阵的读写：
<class 'numpy.ndarray'>
int64
[0 1 2 3 4 5 6 7 8 9] 

多个矩阵的读写：
[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
#以文本方式保存和读取(只适用于一维和二维的数据)
b=np.arange(24).reshape((4,6))
print(b)
np.savetxt('b_txt',b)                    #默认以空格作为分隔符
np.savetxt('b_blank',b,delimiter=',')    #指定逗号为分隔符
lo=np.loadtxt('b_txt')
print("\nload:")
print(lo)
lo_=np.loadtxt('b_blank',delimiter=',')
print(lo_)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

load:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
