In [2]:
import numpy as np
#矩阵的转置、逆矩阵、特征值、特征向量
a=np.arange(12).reshape((3,4))
print("a:\n",a)
print("a的转置:\n",a.T)

b=np.random.randint(0,10,(3,3))
print("b:\n",b)
print("b的逆矩阵:\n",np.linalg.inv(b))
print("b的迹（对角线元素和）:\n",np.trace(b))
val,vec=np.linalg.eig(b)
print("b的特征值:\n",val)
print("b的特征向量:\n",vec)

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a的转置:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
b:
 [[0 5 6]
 [9 5 5]
 [5 4 3]]
b的逆矩阵:
 [[-0.08928571  0.16071429 -0.08928571]
 [-0.03571429 -0.53571429  0.96428571]
 [ 0.19642857  0.44642857 -0.80357143]]
b的迹（对角线元素和）:
 8
b的特征值:
 [14.         -5.23606798 -0.76393202]
b的特征向量:
 [[-0.47062177 -0.78103069  0.1468673 ]
 [-0.73869745  0.59665436 -0.76900715]
 [-0.48253624  0.18437634  0.62213985]]


In [3]:
#对角矩阵diag
a=np.diag((1,2,3))
print("a:\n",a)
b=np.arange(9).reshape((3,3))
print("b:\n",b)
print("提取b的对角线元素：\n",np.diag(b))
print("提取b的上移1对角线元素：\n",np.diag(b,1))
print("提取b的上移2对角线元素：\n",np.diag(b,2))
print("提取b的下移1对角线元素：\n",np.diag(b,-1))


a:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
b:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
提取b的对角线元素：
 [0 4 8]
提取b的上移1对角线元素：
 [1 5]
提取b的上移2对角线元素：
 [2]
提取b的下移1对角线元素：
 [3 7]


In [4]:
#矩阵的合并（vertical stack垂直合并、上下合并；horizontal stack水平合并）
a=np.array([1,1,1])
b=np.array([2,2,2])
c_v=np.vstack((a,b))
print("列合并：\n",c_v)
#因为可以多个同时合并，所以合并的内容要括号括起来
print("多个列合并：\n",np.vstack((a,b,b,a)))
c_h=np.hstack((a,b))
print("行合并：\n",c_h)

列合并：
 [[1 1 1]
 [2 2 2]]
多个列合并：
 [[1 1 1]
 [2 2 2]
 [2 2 2]
 [1 1 1]]
行合并：
 [1 1 1 2 2 2]


In [5]:
#把行向量变成列向量
a=np.array([1,1,1])
print(a.shape)
print(a.T)
print(a.T.shape)
#用转置无法实现行变成列，这时候可以用添加维度
#准守（x,y,x...）的规则添加新的维度 
print("newaxis添加一个维度：")
print(a[:,np.newaxis])                              #newaxis
print(a[:,np.newaxis].shape)
#同样可以把一维的向量变成只有一行的二维矩阵
print("转换为一行三列的矩阵：")
print(a[np.newaxis,:])
print(a[np.newaxis,:].shape)

(3,)
[1 1 1]
(3,)
newaxis添加一个维度：
[[1]
 [1]
 [1]]
(3, 1)
转换为一行三列的矩阵：
[[1 1 1]]
(1, 3)


In [9]:
#指定高维度合并
a=np.arange(24).reshape((2,3,4))
print(a)
b=a.copy()
print("np.concatenate((a,b),axis=0):")                   #concatenate 连接
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=0).shape)
print("np.concatenate((a,b),axis=2):")
print(np.concatenate((a,b),axis=2))
print(np.concatenate((a,b),axis=2).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
np.concatenate((a,b),axis=0):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(4, 3, 4)
np.concatenate((a,b),axis=2):
[[[ 0  1  2  3  0  1  2  3]
  [ 4  5  6  7  4  5  6  7]
  [ 8  9 10 11  8  9 10 11]]

 [[12 13 14 15 12 13 14 15]
  [16 17 18 19 16 17 18 19]
  [20 21 22 23 20 21 22 23]]]
(2, 3, 8)


In [7]:
#矩阵的分割
a=np.arange(12).reshape((3,4))
print("二维情况：")
print(a)
print(np.vsplit(a,3))
print(np.hsplit(a,2))
print("三维情况：")
a=np.arange(24).reshape((2,3,4))
print(a)
print(np.split(a,2,axis=0))
print("将a沿axis=0分成2部分：")
m,n=np.split(a,2,axis=0)
print(m)
print(n)
print("将a在axis=2的轴，分成2段：\n",np.split(a,2,axis=2))
#不等项分割  .array_split
o,p,q=np.array_split(a,3,axis=2)
print("不等项分割：")
print(o)
print(p)
print(q)
#第一个分割两列后面分割一列

二维情况：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
三维情况：
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]]), array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])]
将a沿axis=0分成2部分：
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
将a在axis=2的轴，分成2段：
 [array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
不等项分割：
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
[[[ 2]
  [ 6]
  [10]]

 [[14]
  [18]
  [22]]]
[[[ 3]
  [ 7]
  [11]]

 [